<?php

/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_print_pdf_mpdf_alter().
 */
function inea_core_print_pdf_mpdf_alter(&$mpdf, &$html, &$meta) {
  $mpdf->setAutoBottomMargin = 'stretch';
}

/**
 * Implements hook_webform_submission_insert().
 *
 * Subscribe OR UN-subscribe the user immeadiately
 * (single opt-in/out to/from)  a newsletter.
 */
function inea_core_webform_submission_insert($node, $submission) {
  if ($node->webform['nid'] == '1927') {
    foreach ($submission->data[21] as $newsletter_tid) {
      $mail = $submission->data[3][0];
      $source = 'webform';
      simplenews_subscribe_user($mail, $newsletter_tid, TRUE, $source);
    }
  }
}
