<?php

/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_print_pdf_mpdf_alter().
 */
function inea_core_print_pdf_mpdf_alter(&$mpdf, &$html, &$meta) {
  $mpdf->setAutoBottomMargin = 'stretch';
}

/**
 * Implements hook_webform_submission_insert().
 *
 * Subscribe OR UN-subscribe the user immeadiately
 * (single opt-in/out to/from)  a newsletter.
 */
function inea_core_webform_submission_insert($node, $submission) {
  if ($node->webform['nid'] == '1927') {
    foreach ($submission->data[21] as $newsletter_tid) {
      $mail = $submission->data[3][0];
      $source = 'webform';
      simplenews_subscribe_user($mail, $newsletter_tid, FALSE, $source);
    }
  }
}

/**
 * Implements hook_core_strongarm_alter().
 */
function inea_core_strongarm_alter(&$items) {
  if (!empty($items['media_wysiwyg_wysiwyg_browser_plugins'])) {
    // Prevent platform override.
    $value = array(
      0 => 'upload',
      1 => 'media_browser_plus--media_browser_thumbnails',
      2 => 'media_browser_plus--media_browser_my_files',
      3 => 'media_internet',
    );

    $items['media_wysiwyg_wysiwyg_browser_plugins']->value = $value;
  }
}

/**
 * Implements hook_views_default_views_alter().
 */
function inea_core_views_default_views_alter(&$views) {
  if (isset($views['media_browser_plus'])) {
    // Set the correct titles here.
    $views['media_browser_plus']->display['media_browser_thumbnails']->display_options['title'] = t('Library');
    $views['media_browser_plus']->display['media_browser_my_files']->display_options['title'] = t('My files');
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function inea_core_entity_view_alter(&$build, $type) {
  if ($type == 'file') {
    if (isset($build['field_tags'])) {
      unset($build['field_tags']);
    }
    if (isset($build['field_folder'])) {
      unset($build['field_folder']);
    }
  }
}
