<?php
/**
 * @file
 * Custom INEA module to render some pages and forms.
 */


/**
 * Implements hook_info_alter().
 */
function inea_portal_form_project_node_form_alter(&$form, &$form_state, $form_id) {
  // Disable field body.
  $form['body']['#access'] = 0;
}


/**
 * Implements hook_info_alter().
 */
function inea_portal_form_implementation_success_node_form_alter(&$form, &$form_state, $form_id) {
  // Disable field body.
  $form['body']['#access'] = 0;
}


/**
 * Implements hook_token_info().
 */
function inea_portal_token_info() {
  $info['tokens']['node']['programme'] = array(
    'name' => t('Programme'),
    'description' => t('Returns the url asociated to a programme'),
  );
  $info['tokens']['node']['country'] = array(
    'name' => t('Country'),
    'description' => t('Returns the country associated to the node'),
  );
  return $info;
}

/**
 * Implements hook_tokens().
 */
function inea_portal_tokens($type, $tokens, $data, $options) {
  $replacements = array();
  if ($type == 'node') {
    $node = $data['node'];
    if ($node->type == 'project') {
      foreach ($tokens as $name => $original) {
        switch ($name) {
          case 'programme':
            $tid = $node->field_tag_programme['und'][0]['tid'];
            $term = taxonomy_term_load($tid);
            switch ($term->name) {
              case 'CEF-Energy':
                $name = "connecting-europe-facility/cef-energy";
                $replacements[$original] = $name;
                break;

              case 'CEF-Transport':
                $name = "connecting-europe-facility/cef-transport";
                $replacements[$original] = $name;
                break;

              case 'CEF-Telecom':
                $name = "connecting-europe-facility/cef-telecom";
                $replacements[$original] = $name;
                break;

              case 'TEN-T Projects':
                $name = "ten-t/ten-t-projects";
                $replacements[$original] = $name;
                break;

              default:
                $name = str_replace(" ", "-", drupal_strtolower($term->name));
                break;
            }
            $replacements[$original] = $name;
            break;

          case 'country':
            $countries = $node->field_tag_country['und'];
            if (count($countries) > 1) {
              $name = 'multi-country';
            }
            else {
              $tid = $countries[0]['tid'];
              $term = taxonomy_term_load($tid);
              $name = str_replace(' ', '-', strtolower($term->name));
              $name = preg_replace('/[^A-Za-z0-9\-]/', '', $name);
            }
            $replacements[$original] = $name;
            break;

        }
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_views_data_alter().
 */
function inea_portal_views_data_alter(&$data) {
  $data['field_data_field_project_summary']['field_project_summary_value']['sort'] = array(
    'field' => 'field_project_summary_value',
    'table' => 'field_data_field_project_summary',
    'handler' => 'views_handler_sort',
    'additional_fields' => array('field_project_summary_value','field_project_summary_format'),
    'field_name' => 'field_project_summary',
  );
}
